### ISSUE TITLE
Support for intercept callback

### ISSUE THREAD

**Issue by swalladge** [aresch/pyenet#1]
The enet library has support for setting a function to use to intercept incoming packets before enet processes them (see [this commit](https://github.com/lsalzman/enet/commit/2d979ceb5111faafd2bc78dbaa8893ac36931875)).

Would it be possible to support this in pyenet?

**Comment by aresch** [comment]
It might be, but I don't think it's something that I will take the time to implement.  I would be more than willing to review a pull request if you want to implement it.
