### ISSUE TITLE
enet web address update

### ISSUE THREAD

**Issue by whbdupree** [aresch/pyenet#11]
When I ran `python3 setup.py build`, pyenet gave me this message:

You need to download and extract the enet 1.3 source to enet/
Download the source from: http://enet.bespin.org/SourceDistro.html
See the README for more instructions

That web address is incorrect. It should be changed to 

http://enet.bespin.org/Downloads.html

**Comment by whbdupree** [comment]
i created a pull request (i think?). let me know if you can't see it

**Comment by whbdupree** [comment]
:| i have no idea how to use these github features. sorry

**Comment by LinuxDonald** [comment]
is that not fixed with: https://github.com/aresch/pyenet/commit/22f688fb1bd79b2dbe20391ba9a3341a5f0ca679

**Comment by whbdupree** [comment]
yes that fixed it. that was officially my first contribution to an open source project. changing a web url!!
