### ISSUE TITLE
Server not working properly?

### ISSUE THREAD

**Issue by Amerikranian** [aresch/pyenet#16]
``#Client code
import enet
host = enet.Host(None, 1, 0, 0, 0)
peer = host.connect(enet.Address(b"localhost", 54301), 1)
while 1:
    event = host.service(1000)
    if event.type == enet.EVENT_TYPE_CONNECT:
        print("%s: CONNECT" % event.peer.address)
        break
``#server code
import enet
host = enet.Host(enet.Address(b"localhost", 54301), 10, 0, 0, 0)
while 1:
    # Wait 1 second for an event
    event = host.service(1000)
    if event.type == enet.EVENT_TYPE_CONNECT:
        print("%s: CONNECT" % event.peer.address)
        break

**Comment by Amerikranian** [comment]
Sorry, here's a better version
``#server code
``import enet
``host = enet.Host(enet.Address(b"localhost", 54301), 10, 0, 0, 0)
``while 1:
``    # Wait 1 second for an event
``    event = host.service(0)
``    if event.type == enet.EVENT_TYPE_CONNECT:
``        print("%s: CONNECT" % event.peer.address)
``        break
``#client code
``import enet
``host = enet.Host(None, 1, 0, 0, 0)
``peer = host.connect(enet.Address(b"localhost", 54301), 1)
``while 1:
``    event = host.service(1000)
``    if event.type == enet.EVENT_TYPE_CONNECT:
``        print("%s: CONNECT" % event.peer.address)
``        break

**Comment by Amerikranian** [comment]
[network.zip](https://github.com/aresch/pyenet/files/3673336/network.zip)
I can't get the code styling right so... here you go. This folder contains my client and server code in different files

**Comment by aresch** [comment]
What is the issue that you're experiencing?

**Comment by Amerikranian** [comment]
The issue is that the client seems to connect fine, but the server does not recognize that somebody has, in fact, connected.  You will see that I tell the interpreter to print any event that is not of type none out on the screen, and when the client connects to it, the server output stays blank.  The expected output is for it to detect the connection and the fact that the client promptly leaves as soon as it is connected.  The last part is on purpose, I wanted to experiment with sending data later after I managed to successfully connect.

**Comment by aresch** [comment]
Your code looks similar to what is in the test_client.py and test_server.py code. Do those work? Also, I'd suggest not passing 0 into host.service() in your server code as it will cause a tight spin.

**Comment by Amerikranian** [comment]
The test_client and test_server work properly, by which I mean I can connect, and the client shuts down the server. That's what makes this weird. Literally, I pretty much copied the test_client and test_server and edited them to just do connections.
What value would you suggest me pass into the service method? I thought 0 was the best and most quickest response the server will have towards the received packets

**Comment by aresch** [comment]
host.service() will return when an event is posted, so it just depends on if you need to do anything else in your loop. 1000ms seems like a reasonable value.

So the reason you're not getting the event on the server side is that you need to call host.service() once more on the client side before exiting.

If you change your client code to the following, it should work as expected:

```python
import enet
host = enet.Host(None, 1, 0, 0, 0)
peer = host.connect(enet.Address(b"localhost", 54301), 1)
while 1:
    event = host.service(1000)
    if event.type == enet.EVENT_TYPE_CONNECT:
        print("%s: CONNECT" % event.peer.address)
        host.service(0)
        break
```
I don't really have a good answer for you besides that there may be something to do with the handshake that's not being done in the client without the additional host.service() call.

Hope this helps.
