### ISSUE TITLE
Is it possible to connect pyenet to enet in C++ program?

### ISSUE THREAD

**Issue by mar4ello6** [aresch/pyenet#19]
I tried to connect pyenet to C++ program's enet server. But pyenet didn't connect. I used test_client.py to connect. (Ofc I changed ip and port)

**Comment by aresch** [comment]
Yes, it should be possible. If you can't get it to work, there may be a bug in pyenet or your code. You should also make sure you're using the same version of enet in both the Python client and the C++ server.
