### ISSUE TITLE
what is enet_host_destroy in pyenet?

### ISSUE THREAD

**Issue by HanzHaxors** [aresch/pyenet#20]
Maybe im a little dumb or what, but i really need your help guys.
So i make a new function:
```python
def disconnect():
    # enet_host_destroy(server)
    exit()
```
so my question is, is there any method like `enet_host_destroy` in this package? if there's any, where i should find it?

Thanks

**Comment by aresch** [comment]
https://github.com/aresch/pyenet/blob/acb3d78731e587e3d07f349af649d9af025fe655/enet.pyx#L882

The __dealloc__ method on the Host object should do this for you when the Host gets deleted.
