### ISSUE TITLE
Socket.send wrapper for enet_socket_send

### ISSUE THREAD

**Issue by noway421** [aresch/pyenet#3]
Would be nice to have that one too for calling `enet_socket_send`. The signature would be

```python
cdef class Socket:
    def send(self, Address address, data):
```

**Comment by noway421** [comment]
I have the patch for that (which works at least against enet 1.3.3), tell me if you interested in a PR

**Comment by noway421** [comment]
Would it be ok to combine it with the intercept callback patch? The game we are working on relies on those 2 features, and testing them separately is complicated because the game requires both of them at the same time

**Comment by aresch** [comment]
Yes, that would be fine.
